version: "3"

services:
    mysql:
        image: mysql:5.7
        container_name: cn_mysql_sistore
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sistoreid_db
            MYSQL_USER: sistore
            MYSQL_PASSWORD: s1st0r3_1d
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - nginx_laravel

    php:
        image: sholihin/php-fpm:php73-sistore
        container_name: cn_sistoreid
        restart: always
        depends_on:
            - mysql
        volumes:
            - ./laravel_code:/var/www/html
        networks:
            - nginx_laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: cn_phpmyadmin_sistore
        restart: always
        depends_on:
            - mysql
        ports: 
            - "8080:80"
        environment: 
            PMA_HOSTS: cn_mysql_sistore
            MYSQL_USERNAME: sistore
            MYSQL_ROOT_PASSWORD: s1st0r3_1d
        networks:
            - nginx_laravel

    nginx:
        image: nginx
        container_name: cn_nginx_sistore
        restart: always
        depends_on: 
            - php
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./laravel_code:/var/www/html
            - ./ssl:/etc/ssl/private
            - ./conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks: 
            - nginx_laravel
networks:
    nginx_laravel:
        driver: bridge

volumes:
    # laravel_code:
    mysql_data: